modLoader="javafml"
license="${mod_license}"
loaderVersion="${loader_version_range}"
issueTrackerURL="${mod_issue_tracker}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="URL"
#displayURL="URL"
#logoFile="logo.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"