package xiroc.dungeoncrawl.dungeon.segment;

public enum DungeonSegmentModelBlockType {

	CEILING, CEILING_STAIRS_NORTH, CEILING_STAIRS_EAST, CEILING_STAIRS_SOUTH, CEILING_STAIRS_WEST, WALL, WALL_LOG, FLOOR, FLOOR_STAIRS_NORTH, FLOOR_STAIRS_EAST, FLOOR_STAIRS_SOUTH, FLOOR_STAIRS_WEST, STAIRS, STAIRS_NORTH, STAIRS_EAST,
	STAIRS_SOUTH, STAIRS_WEST, SPAWNER, CHEST_COMMON, RAND_FLOOR_CHESTCOMMON_SPAWNER, TRAPDOOR, OTHER;

}
