package xiroc.dungeoncrawl.dungeon.segment;

public enum DungeonSegmentModelBlockType {

	NONE, CEILING, CEILING_STAIRS, WALL, WALL_LOG, FLOOR, FLOOR_STAIRS, STAIRS, SPAWNER, CHEST_COMMON, RAND_FLOOR_CHESTCOMMON_SPAWNER, TRAPDOOR, TORCH, TORCH_DARK, OTHER;

}
